# ========== Profile ========== #
# avatar
avatar: https://mizuka-blog.oss-cn-shanghai.aliyuncs.com/static/avatar/Mizuka.jpg
# author name
author: Mizuka
# signature
signature: 知行合一
# SNS
social:
  email: mizuka.wu@outlook.com
  github: //github.com/mizuka-wu
  # wechat and qq should be a path of qr-code image
  wechat: https://mizuka-blog.oss-cn-shanghai.aliyuncs.com/static/assets/example_qr.png
  zhihu: 
  twitter: 
  instagram: 
  bilibili: https://space.bilibili.com/1383044/
  rss: /atom.xml
# friends
friends:
  我的项目: //www.baidu.com
  friendB: //www.google.com
  friendC: 
about:
  enable: true
  image: 'https://mizuka-blog.oss-cn-shanghai.aliyuncs.com/static/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site
SEO_title: 水华的博客
# main title
main_title: 水华的博客
# subtitle
subtitle: 这年头决定命运的，是情报
# site haeder image
site_header_image: 'https://mizuka-blog.oss-cn-shanghai.aliyuncs.com/static/intro/index-bg.jpg'
# post haeder image
post_header_image: 'https://mizuka-blog.oss-cn-shanghai.aliyuncs.com/static/intro/post-bg.jpg'
# 404 image
_404_image: 'https://source.unsplash.com/random'

# ========== Search ========== #
algolia_search:
  enable: true
  hits:
    per_page: 10 # 每页的结果数
  labels:
    input_placeholder: 搜索模式，启动！ # 搜索栏 placeholder
    hits_empty: "什么都没找到呢～" # 搜索结果提示
    hits_stats: "搜索到了${hits}条结果！ （${time} ms）" # 搜索无结果的提示

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: "0eAmMMUxqe9alLwt4KzftCnv-gzGzoHsz"
  valine_appKey: "PfYhgvohzSQStMaJHaneYXq9"
  valine_placeHolder: 给我个留言吧！

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: false
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: UA-112738831-1
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
